sudo: required
services:
  - docker

before_install:
  - docker build -t zigavucko/docker-react -f Dockerfile.dev .

script:
  # `-e CI=true` argument will force Jest to run in CI-mode, and tests will only run once instead of launching the watcher.
  - docker run -e CI=true zigavucko/docker-react yarn test --coverage
